project:
  type: website
  output-dir: _site

website:
  title: "Chanseok Kang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publication.qmd
        text: Publication
    right: 
      - href: ../kr
        text: Kr
      - href: https://github.com/goodboychan
        icon: github
      - href: https://www.linkedin.com/in/chanseokk/
        icon: linkedin
        
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



